export const skills = [
  "React",
  "React Hooks",
  "React Router",
  "NPM",
  "Redux",
  "Redux (Toolkit)",
  "Redux-Saga",
  "GitHub Pull Requests & Review",
  "Git",
  "Working with API (fetch, axios)",
  "Promises, Async/Await",
  "Error handling",
  "ES6+",
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Immutability",
  "CSS Flexbox",
  "CSS Grid",
  "CSS BEM convention",
  "Markdown",
  "Trello",
  "Project Manager expierience",
  "IT Project Manager experience",
  "WCAG basic knowlage", 
];

export const toLearn = [
  "Wordpress development",  
  "Mobile app development",
  "WCAG",
];