export const skills = [
  "React",
  "React Hooks",
  "React Router",
  "NPM",
  "Redux",
  "Redux (Toolkit)",
  "Redux-Saga",
  "GitHub Pull Requests & Review",
  "Git",
  "Working with API (fetch, axios)",
  "Promises, Async/Await",
  "Error handling",
  "ES6+",
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Immutability",
  "CSS Flexbox",
  "CSS Grid",
  "CSS BEM convention",
  "Markdown",
  "Trello",
  "Scrum basic knowledge",
  "WordPress",
  "WCAG basic knowledge", 
  "Photoshop basic knowledge",
  "Project Manager experience",
  "IT Project Manager experience",  
];

export const toLearn = [
  "TypeScript", 
  "Cypress", 
  "Mobile app development"
];