export const skills = [
  "React",
  "React Hooks",
  "React Router",
  "Git",
  "GitHub Pull Requests & Review",
  "NPM",
  "Redux",
  "Redux (Toolkit)",
  "Redux-Saga",
  "Working with API (fetch, axios)",
  "Promises, Async/Await",
  "Error handling",
  "ES6+",
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Immutability",
  "CSS Flexbox",
  "CSS Grid",
  "CSS BEM convention",
  "Markdown",
  "Scrum",
  "Trello",
  "WCAG - basics",
  "WordPress - basics",
  "Photoshop - basics",
  "IT Project Manager experience",
  "Project Manager experience",
];

export const toLearn = [
  "TypeScript",
  "TanStack Query",
  "SASS"
];